# This is a basic workflow to help you get started with Actions

name: Documention

# Controls when the workflow will run
on:
  push:
    branches: [ main ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v2
        with:
          python-version: 3.7
      - name: Get Poetry
        uses: abatilo/actions-poetry@v2.1.3
      - name: Install Dependencies
        run: poetry install
      - name: Generate Documentation
        run: poetry run pdoc3 shell_source -f --html -o docs --config show_source_code=False
      - name: Check for modified files
        id: git-check
        run: echo ::set-output name=modified::$(if git diff-index --quiet HEAD --; then echo "false"; else echo "true"; fi)
      - name: Create Pull Request
        if: steps.git-check.outputs.modified == 'true'
        uses: peter-evans/create-pull-request@v3
        with:
          title: Generate Documentation
          commit-message: generated docs with pdoc3
          branch: documentation
          token: ${{ secrets.PERSONAL_GH_TOKEN }}
          labels: automerge,documentation
