# This is a basic workflow to help you get started with Actions

name: Publish

on:
  release:
    types:
      - created

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v2
        with:
          python-version: 3.7
      - name: Get Poetry
        run: pip install poetry
      - name: Build Package
        run: poetry build
      - name: Check Build
        run: pip install dist/*.whl
      - name: Set POETRY_VERSION environment variable
        run: echo "POETRY_VERSION=$(poetry version -s)" >> $GITHUB_ENV
      - name: Build and Publish Conda Package
        uses: amauryval/publish_conda_package_action@2.0.3
        with:
          CondaDir: 'conda-recipe'
          Channels: 'conda-forge'
          Platforms: 'noarch'
          CondaUsername: ${{ secrets.ANACONDA_USERNAME }}
          CondaPassword: ${{ secrets.ANACONDA_PASSWORD }}
      - name: Publish Pip Package
        run: poetry publish -u ${{ secrets.PYPI_USERNAME }} -p ${{ secrets.PYPI_PASSWORD }}