# This is a basic workflow to help you get started with Actions

name: Publish

# Controls when the workflow will run
on:
  release:
    types:
      - created

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v2
        with:
          python-version: 3.7
      - name: Get Poetry
        uses: abatilo/actions-poetry@v2.1.3
      - name: Build Package
        run: poetry build
      - name: Check Build
        run: pip install dist/*.whl
      - name: Publish Package
        run: poetry publish -u ${{ secrets.PYPI_USERNAME }} -p ${{ secrets.PYPI_PASSWORD }}
