name: Test
on:
  pull_request:
    branches:
      - main
    paths-ignore:
      - shell_source/**
      - tests/**

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Skip Tests (Code unchanged)
        run: echo "No tests required. Source code didn't change."
