name: Tests
on:
  pull_request:
    branches:
      - main
    paths:
      - shell_source/**
      - tests/**
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest
    if: "! contains(github.event.pull_request.labels.*.name, 'notest')"
    steps:
      - name: Check out repository code
        uses: actions/checkout@v3
      - name: Get Shells
        run: sudo apt install -y bash zsh ksh fish tcsh
      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.7
      - name: Get Poetry
        run: pip install poetry
      - name: Install
        run: poetry install
      - name: Run Tests
        run: poetry run pytest
